#print(client.getinfo())
#client.create("steam","iot001",False)
#print(client.getmultibalances())
#client.issuemore(client.listaddresses()[0]['address'],"dellserver",1)
#print(client.getmultibalances())
#print(client.listaddresses())
#print(client.listassets())
#client.send("1XXXXXXWrHXXXXXXQtXXXXXXYcXXXXXXZaY3hj","60-265-64467","1")
#client.issue(client.listaddresses()[0]['address'], {"name":"asset1","open":True},1)
#client.issuemore(client.listaddresses()[0]['address'],"asset1",1)
#client.grant("1XXXXXXWrHXXXXXXQtXXXXXXYcXXXXXXZaY3hj","receive")
#client.create("steam","iot001",False)
#client.issue(client.listaddresses()[0]['address'],"dellserver",600,1)
#print(client.getmultibalances())
#print(client.sendasset("1XXXXXXWrHXXXXXXQtXXXXXXYcXXXXXXZaY3hj","65-266-2074",100))

